// src/api.ts

// -------- Basic types --------
export type UserRole = "runner" | "coach";

export const API_BASE = "http://localhost:8000";

export interface User {
  id: string;
  name: string;
  role: UserRole;
  runner_code?: number | null;
}

// -------- Dashboard types --------

export interface DashboardOverview {
  total_sessions: number;
  total_distance_km: number;
  total_duration_seconds: number;
  estimated_calories: number;
}

export interface DailyStat {
  date: string;
  sessions: number;
  distance_km: number;
  duration_seconds: number;
}

export interface TimeOfDayItem {
  slot: "morning" | "forenoon" | "afternoon" | "evening" | "night" | string;
  sessions: number;
  distance_km: number;
  duration_seconds: number;
  percentage: number;
}

export interface TrainingLoadWeek {
  week_label: string;
  week_start: string;
  training_load: number;
}

export interface DashboardResponse {
  overview: DashboardOverview;
  daily: {
    range_days: number;
    daily: DailyStat[];
  };
  time_of_day: {
    range_days: number;
    time_of_day_distribution: TimeOfDayItem[];
    total_sessions: number;
  };
  training_load: {
    range_weeks: number;
    weeks: TrainingLoadWeek[];
    current_week_load: number;
    average_week_load: number;
  };
}

// -------- Run record types --------

export interface TodayRunRecordResponse {
  timezone: string;
  date: string;
  settings: {
    user_id: string;
    calories_per_hour: number;
  };
  active_session: {
    session_id: string;
    started_at: string;
    calories_per_hour: number;
    elapsed_seconds: number;
    is_paused: boolean;
  } | null;
  today_summary: {
    total_duration_seconds: number;
    total_calories: number;
    total_distance_km: number;
    sessions: Array<{
      id: string;
      started_at: string;
      ended_at: string | null;
      total_distance_km: number;
      total_duration_seconds: number;
      total_calories: number;
    }>;
  };
  // Newly added: today's goal total seconds (calculated by backend)
  today_goal_seconds?: number;
}

// -------- Running plan types --------

export interface RunningPlanItem {
  id: string;
  start_time: string;
  duration_minutes: number;
  distance_km: number;
  activity: string | null;
  description?: string | null; // ✅ optional description
}

export interface RunningPlanCalendarDay {
  date: string; // YYYY-MM-DD
  weekday: number; // 0–6
  is_today: boolean;
  plans: RunningPlanItem[];
}

export interface RunningPlanCalendarResponse {
  timezone: string;
  year: number;
  month: number;
  days: RunningPlanCalendarDay[];
}

// Compatible with the alias used in RunningPlan.tsx
export type RunningPlanDayPlan = RunningPlanItem;

export interface DayPlanCreatePayload {
  date: string; // YYYY-MM-DD
  start_time: string; // HH:MM
  duration_minutes: number;
  distance_km: number;
  activity?: string;
  description?: string; // ✅ 新增：创建 day plan 时也可以带描述
}

// Compatible import name in RunningPlan.tsx
export type DayPlanCreateRequest = DayPlanCreatePayload;

/// -------- AI weekly plan types --------

export interface AiPlanPreviewActivity {
  start_time: string;
  duration_minutes: number;
  distance_km: number;
  activity: string;
  // Optional description text generated by backend
  description?: string;
}

export interface AiPlanPreviewDay {
  weekday: number; // 0-6
  activities: AiPlanPreviewActivity[];
}

export interface AiPlanPreviewRequest {
  height_cm: number;
  weight_kg: number;
  age: number;
  goal_type?: string;
  target_distance_m?: number;
  target_weight_kg?: number;

  // ✅ NEW: fitness level ("beginner" | "intermediate" | "advanced")
  fitness_level?: string;

  weekly_slots: Array<{
    weekday: number; // 0-6
    start_time: string; // HH:MM
    end_time: string; // HH:MM
  }>;
}

// Compatible import name in RunningPlan.tsx
export type AiPlanGenerateRequest = AiPlanPreviewRequest;

export interface AiPlanPreviewResponse {
  user_params: {
    height_cm: number;
    weight_kg: number;
    age: number;
    goal_type?: string;
    target_distance_m?: number;
    target_weight_kg?: number;

    // ✅ echo back from backend if you like
    fitness_level?: string;
  };
  weekly_template: AiPlanPreviewDay[];
}

export interface AiPlanApplyRequestDay {
  weekday: number;
  activities: AiPlanPreviewActivity[];
}

export interface AiPlanApplyRequest {
  weekly_template: AiPlanApplyRequestDay[];
  start_date?: string; // "YYYY-MM-DD"
  days?: number;
}


// -------- Coach <-> Runner types --------

export interface BoundRunner {
  id: string;
  name: string;
  runner_code: number;
}

export interface CoachNote {
  id: string;
  runner_id: string;
  coach_id: string;
  coach_name?: string | null;
  content: string;
  created_at: string; // ISO string
}

// =====================================
// Generic request wrapper
// =====================================

async function request<T>(path: string, options: RequestInit = {}): Promise<T> {
  const resp = await fetch(`${API_BASE}${path}`, {
    headers: {
      "Content-Type": "application/json",
      ...(options.headers || {}),
    },
    ...options,
  });

  if (!resp.ok) {
    let detail = `HTTP ${resp.status}`;
    try {
      const data = await resp.json();
      if (data && (data as any).detail) {
        detail = JSON.stringify((data as any).detail);
      }
    } catch {
      // ignore parse error
    }
    throw new Error(detail);
  }

  if (resp.status === 204) {
    // No content
    return {} as T;
  }

  return (await resp.json()) as T;
}

// =====================================
// Auth
// =====================================

export async function registerUser(
  username: string,
  role: UserRole
): Promise<User> {
  const body = { username, role };
  return request<User>("/api/auth/register", {
    method: "POST",
    body: JSON.stringify(body),
  });
}

/**
 * Login: must provide username + role
 */
export async function loginUser(
  username: string,
  role: UserRole
): Promise<User> {
  const body = { username, role };
  return request<User>("/api/auth/login", {
    method: "POST",
    body: JSON.stringify(body),
  });
}

// =====================================
// Dashboard
// =====================================

export async function fetchDashboard(
  userId: string,
  days: number,
  weeks: number
): Promise<DashboardResponse> {
  const q = `?days=${days}&weeks=${weeks}`;
  return request<DashboardResponse>(`/api/dashboard/${userId}${q}`);
}

// =====================================
// Run record & user settings
// =====================================

export async function fetchTodayRunRecord(
  userId: string
): Promise<TodayRunRecordResponse> {
  return request<TodayRunRecordResponse>(`/api/run_record/today/${userId}`);
}

export async function fetchUserSettingsApi(
  userId: string
): Promise<{ user_id: string; calories_per_hour: number }> {
  return request<{ user_id: string; calories_per_hour: number }>(
    `/api/user_settings/${userId}`
  );
}

export async function updateCaloriesPerHourApi(
  userId: string,
  caloriesPerHour: number
): Promise<{ user_id: string; calories_per_hour: number }> {
  return request<{ user_id: string; calories_per_hour: number }>(
    `/api/user_settings/${userId}/calories_per_hour`,
    {
      method: "POST",
      body: JSON.stringify({ calories_per_hour: caloriesPerHour }),
    }
  );
}

// Compatible with old name: RunRecord.tsx uses setCaloriesPerHourApi
export async function setCaloriesPerHourApi(
  userId: string,
  caloriesPerHour: number
): Promise<{ user_id: string; calories_per_hour: number }> {
  return updateCaloriesPerHourApi(userId, caloriesPerHour);
}

// ---- Run session control ----

export async function startRunSession(
  userId: string,
  note?: string
): Promise<any> {
  return request(`/api/run/start/${userId}`, {
    method: "POST",
    body: JSON.stringify({ note: note ?? null }),
  });
}

export async function pauseRunSession(userId: string): Promise<any> {
  return request(`/api/run/pause/${userId}`, {
    method: "POST",
  });
}

export async function resumeRunSession(userId: string): Promise<any> {
  return request(`/api/run/resume/${userId}`, {
    method: "POST",
  });
}

export async function stopRunSession(
  userId: string,
  totalDistanceKm?: number,
  elapsedSeconds?: number
): Promise<any> {
  return request(`/api/run/stop/${userId}`, {
    method: "POST",
    body: JSON.stringify({
      total_distance_km:
        typeof totalDistanceKm === "number" ? totalDistanceKm : null,
      elapsed_seconds:
        typeof elapsedSeconds === "number" ? elapsedSeconds : null,
    }),
  });
}

// Compatible names imported in RunRecord.tsx
export async function startRunApi(
  userId: string,
  note?: string
): Promise<any> {
  return startRunSession(userId, note);
}

export async function pauseRunApi(userId: string): Promise<any> {
  return pauseRunSession(userId);
}

export async function resumeRunApi(userId: string): Promise<any> {
  return resumeRunSession(userId);
}

export async function stopRunApi(
  userId: string,
  totalDistanceKm?: number,
  elapsedSeconds?: number
): Promise<any> {
  return stopRunSession(userId, totalDistanceKm, elapsedSeconds);
}

// =====================================
// Running plan calendar / daily plan
// =====================================

export async function fetchRunningPlanCalendarApi(
  userId: string,
  year: number,
  month: number
): Promise<RunningPlanCalendarResponse> {
  const q = `?year=${year}&month=${month}`;
  return request<RunningPlanCalendarResponse>(
    `/api/running_plan/calendar/${userId}${q}`
  );
}

// Compatible with RunningPlan.tsx
export async function fetchRunningPlanCalendar(
  userId: string,
  year: number,
  month: number
): Promise<RunningPlanCalendarResponse> {
  return fetchRunningPlanCalendarApi(userId, year, month);
}

export async function createDayPlanApi(
  userId: string,
  payload: DayPlanCreatePayload
): Promise<RunningPlanItem> {
  return request<RunningPlanItem>(`/api/running_plan/day/${userId}`, {
    method: "POST",
    body: JSON.stringify(payload),
  });
}

export async function deleteDayPlanApi(
  userId: string,
  planId: string
): Promise<void> {
  await request(`/api/running_plan/day/${userId}/${planId}`, {
    method: "DELETE",
  });
}

// =====================================
// AI weekly test plan
// =====================================

export async function previewAiPlan(
  userId: string,
  payload: AiPlanPreviewRequest
): Promise<AiPlanPreviewResponse> {
  return request<AiPlanPreviewResponse>(
    `/api/running_plan/ai/preview/${userId}`,
    {
      method: "POST",
      body: JSON.stringify(payload),
    }
  );
}

export async function applyAiPlan(
  userId: string,
  payload: AiPlanApplyRequest
): Promise<any> {
  return request(`/api/running_plan/ai/apply/${userId}`, {
    method: "POST",
    body: JSON.stringify(payload),
  });
}


// =====================================
// Coach <-> Runner bind & notes
// =====================================

export async function fetchCoachRunners(
  coachId: string
): Promise<BoundRunner[]> {
  return request<BoundRunner[]>(`/api/coach/${coachId}/runners`);
}

export async function bindRunnerByCode(
  coachId: string,
  runnerCode: number
): Promise<BoundRunner> {
  return request<BoundRunner>(`/api/coach/${coachId}/bind_runner`, {
    method: "POST",
    body: JSON.stringify({
      runner_code: runnerCode,
    }),
  });
}

// Fetch all coach notes for a runner (used by both coach and runner)
export async function fetchRunnerNotes(
  runnerId: string
): Promise<CoachNote[]> {
  return request<CoachNote[]>(`/api/runner/${runnerId}/notes`);
}

// Coach adds a new note for a runner
export async function createCoachNoteApi(
  coachId: string,
  runnerId: string,
  content: string
): Promise<CoachNote> {
  return request<CoachNote>(`/api/coach/${coachId}/runner/${runnerId}/notes`, {
    method: "POST",
    body: JSON.stringify({ content }),
  });
}
